Feature/menu/adding logs to cli menu advanced flow
Miquilin/SearchFiles_125 pull request #30
Opened 2018-02-15 09:53 UTC by Miquilin

Added the needed logs to CLIMenuAdvancedFlow class

2018-02-15 23:31 UTC, ovandononi requested changes
Obs 1: there are still some commented lines
Obs 2: Unit test are failed
To verify it, add to the end the following lines on src/com/jalasoft/search_files/menu/cli_menu_advanced_flow.py: 
if __name__ == "__main__":
    unittest.main()

{code}
----------------------------------------------------------------------
Ran 116 tests in 0.091s

FAILED (failures=10)
{code}

2018-02-16 10:27 UTC, Miquilin commented
I forgot to comment about the code that is commented in some functions, it is due to I am mocking the return data formthe validation menu function in order to have running the advanced menu. This part of the code (menu_validations) was implemented by @Saex05 and was completed yesterday and merged today to the develop.
About the unit test failing , these all are related to the new validations implemented by @Saex05 
I don't know if it possible to do the merge of this code related to the logs, because I will work on these observations in another branch. Do you agree @ovandononi, @Saex05, @jpsandovaln ??

2018-02-16 18:48 UTC, Saex05 approved these changes

2018-02-16 19:30 UTC, Saex05 commented on src/com/jalasoft/search_files/menu/cli_menu_advanced_flow.py
>      def advanced_search_for_content_criteria_validation(self, option):
this method is not yet implemented for this reason the unit test fails
`def test_advanced_search_for_content_criteria_validation_returns_false_when_option_provided_has_non_valid_chars(self):`

2018-02-16 19:54 UTC, Saex05 commented
the logs were correctly applied, the problem with the unit tests are because some methods are not yet  implemented and they are needed the latest validations

2018-02-16 19:56 UTC, merged